import { type Node, type Edge } from 'reactflow';
import { type CableEdgeData } from '../edges/CableEdge';

export const TEMPLATE_MINIMALIST = {
  nodes: [
    {
      id: 'battery-1',
      type: 'battery',
      position: { x: 80, y: 160 },
      data: { label: '12V Batterie', capacity: 100, chemistry: 'AGM' },
    },
    { id: 'ground-1', type: 'ground', position: { x: 80, y: 360 }, data: { label: 'Massepunkt' } },
    { id: 'fusebox-1', type: 'fuse', position: { x: 380, y: 160 }, data: { label: 'Sicherungskasten' } },
    {
      id: 'cons-light',
      type: 'consumer',
      position: { x: 680, y: 60 },
      data: { label: 'LED-Beleuchtung', watts: 20 },
    },
    {
      id: 'cons-usb',
      type: 'consumer',
      position: { x: 680, y: 220 },
      data: { label: 'USB Steckdosen', watts: 36 },
    },
    {
      id: 'cons-cool',
      type: 'consumer',
      position: { x: 680, y: 380 },
      data: { label: 'Kühlbox', watts: 45 },
    },
  ] as Node[],
  edges: [
    // Hauptsicherung sitzt direkt am Batteriepol (≤ 20 cm) und trägt den
    // Gesamtstrom der drei Verbraucher (~8,4 A bei 12 V) → 10 A ATO.
    // Die Minus-Rückleitungen ergänzt „Automatisch verbinden“ fachgerecht
    // (Batterie → Shunt → Minusschiene → Verbraucher); doppelte Rückleiter
    // im Template würden parallele Minuspfade erzeugen.
    {
      id: 'e-batt-fuse',
      source: 'battery-1',
      sourceHandle: 'plus',
      target: 'fusebox-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 0.2, crossSection: 10, fuseSize: 10 },
    },
    {
      id: 'e-batt-gnd',
      source: 'battery-1',
      sourceHandle: 'minus',
      target: 'ground-1',
      targetHandle: 'minus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 10 },
    },
    {
      id: 'e-fuse-light',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-light',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 5, crossSection: 2.5 },
    },
    {
      id: 'e-fuse-usb',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-usb',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 3, crossSection: 2.5 },
    },
    {
      id: 'e-fuse-cool',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-cool',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 2, crossSection: 4 },
    },
  ] as Edge<CableEdgeData>[],
};

export const TEMPLATE_ALLROUNDER = {
  nodes: [
    { id: 'solar-1', type: 'solar', position: { x: 80, y: 60 }, data: { label: '150W Solar', watts: 150 } },
    {
      id: 'starter-1',
      type: 'battery',
      position: { x: 80, y: 240 },
      data: { label: 'Starterbatterie', capacity: 90, chemistry: 'AGM' },
    },
    {
      id: 'battery-1',
      type: 'battery',
      position: { x: 80, y: 440 },
      data: { label: '100Ah Lithium', capacity: 100, chemistry: 'LiFePO4' },
    },
    {
      id: 'charger-1',
      type: 'mpptController',
      position: { x: 380, y: 60 },
      data: { label: 'MPPT Solarregler', amps: 30 },
    },
    {
      id: 'charger-2',
      type: 'dcdcCharger',
      position: { x: 380, y: 240 },
      data: { label: 'DC-DC Ladebooster', amps: 30 },
    },
    { id: 'busbar-plus', type: 'busbar', position: { x: 380, y: 440 }, data: { label: 'Plus Busbar' } },
    { id: 'busbar-minus', type: 'busbar', position: { x: 380, y: 620 }, data: { label: 'Minus Busbar' } },
    { id: 'fusebox-1', type: 'fuse', position: { x: 680, y: 200 }, data: { label: 'Sicherungskasten' } },
    {
      id: 'inverter-1',
      type: 'inverter',
      position: { x: 680, y: 440 },
      data: { label: '500W Inverter', watts: 500 },
    },
    {
      id: 'cons-fridge',
      type: 'consumer',
      position: { x: 980, y: 60 },
      data: { label: 'Kompressorkühlschrank', watts: 60 },
    },
    {
      id: 'cons-pump',
      type: 'consumer',
      position: { x: 980, y: 220 },
      data: { label: 'Wasserpumpe', watts: 40 },
    },
    {
      id: 'cons-light',
      type: 'consumer',
      position: { x: 980, y: 380 },
      data: { label: 'LED-Beleuchtung', watts: 20 },
    },
    {
      id: 'cons-230v',
      type: 'consumer230v',
      position: { x: 980, y: 540 },
      data: { label: '230V Steckdose', watts: 300 },
    },
  ] as Node[],
  edges: [
    {
      id: 'e-batt-plus',
      source: 'battery-1',
      sourceHandle: 'plus',
      target: 'busbar-plus',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 0.5, crossSection: 35, fuseSize: 100 },
    },
    {
      id: 'e-batt-minus',
      source: 'battery-1',
      sourceHandle: 'minus',
      target: 'busbar-minus',
      targetHandle: 'minus',
      type: 'cableEdge',
      data: { length: 0.5, crossSection: 35 },
    },
    {
      id: 'e-solar-charger',
      source: 'solar-1',
      sourceHandle: 'plus',
      target: 'charger-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 3, crossSection: 6 },
    },
    {
      id: 'e-charger-busbar',
      source: 'charger-1',
      sourceHandle: 'plus',
      target: 'busbar-plus',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 10, fuseSize: 40 },
    },
    {
      id: 'e-starter-dcdc',
      source: 'starter-1',
      sourceHandle: 'plus',
      target: 'charger-2',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 5, crossSection: 16, fuseSize: 60 },
    },
    {
      id: 'e-dcdc-busbar',
      source: 'charger-2',
      sourceHandle: 'plus',
      target: 'busbar-plus',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 16, fuseSize: 50 },
    },
    {
      id: 'e-busbar-fuse',
      source: 'busbar-plus',
      sourceHandle: 'plus',
      target: 'fusebox-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 16 },
    },
    {
      id: 'e-fuse-fridge',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-fridge',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 3, crossSection: 4 },
    },
    {
      id: 'e-fuse-pump',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-pump',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 4, crossSection: 2.5 },
    },
    {
      id: 'e-fuse-light',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-light',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 5, crossSection: 1.5 },
    },
    {
      id: 'e-busbar-inv-plus',
      source: 'busbar-plus',
      sourceHandle: 'plus',
      target: 'inverter-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 25, fuseSize: 60 },
    },
    {
      id: 'e-busbar-inv-minus',
      source: 'busbar-minus',
      sourceHandle: 'minus',
      target: 'inverter-1',
      targetHandle: 'minus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 25 },
    },
    {
      id: 'e-inv-230',
      source: 'inverter-1',
      sourceHandle: 'plus',
      target: 'cons-230v',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 2, crossSection: 2.5, edgeDomain: 'AC_230V' },
    },
  ] as Edge<CableEdgeData>[],
};

export const TEMPLATE_AUTARK = {
  nodes: [
    { id: 'solar-1', type: 'solar', position: { x: 80, y: 60 }, data: { label: '400W Solar', watts: 400 } },
    {
      id: 'starter-1',
      type: 'battery',
      position: { x: 80, y: 240 },
      data: { label: 'Starterbatterie', capacity: 90, chemistry: 'AGM' },
    },
    {
      id: 'shore-1',
      type: 'shorePower',
      position: { x: 80, y: 420 },
      data: { label: 'Landstrom', hasRcd: true },
    },
    {
      id: 'battery-1',
      type: 'battery',
      position: { x: 80, y: 600 },
      data: { label: '200Ah Lithium', capacity: 200, chemistry: 'LiFePO4' },
    },
    {
      id: 'charger-1',
      type: 'mpptController',
      position: { x: 380, y: 60 },
      data: { label: 'MPPT Solarregler', amps: 30 },
    },
    {
      id: 'charger-2',
      type: 'dcdcCharger',
      position: { x: 380, y: 240 },
      data: { label: 'DC-DC Ladebooster', amps: 30 },
    },
    { id: 'busbar-plus', type: 'busbar', position: { x: 380, y: 500 }, data: { label: 'Plus Busbar' } },
    { id: 'busbar-minus', type: 'busbar', position: { x: 380, y: 680 }, data: { label: 'Minus Busbar' } },
    { id: 'fusebox-1', type: 'fuse', position: { x: 680, y: 200 }, data: { label: 'Sicherungskasten' } },
    // 1500 W Wechselrichter: ~138 A DC-Eingangsstrom bei 12,8 V — das lässt
    // sich mit der Normreihe (max. 70 mm² / 160 A Sicherung) fehlerfrei
    // absichern. Ein 2000-W-Wechselrichter (~184 A) läge über jeder
    // zulässigen Sicherung der Normreihe und zeigte dauerhaft Fehler.
    {
      id: 'inverter-1',
      type: 'inverter',
      position: { x: 680, y: 480 },
      data: { label: '1500W Inverter', watts: 1500, continuousPower: 1500 },
    },
    {
      id: 'cons-fridge',
      type: 'consumer',
      position: { x: 980, y: 60 },
      data: { label: 'Kompressorkühlschrank', watts: 60 },
    },
    {
      id: 'cons-heat',
      type: 'consumer',
      position: { x: 980, y: 220 },
      data: { label: 'Standheizung', watts: 40 },
    },
    { id: 'cons-fan', type: 'consumer', position: { x: 980, y: 380 }, data: { label: 'MaxxFan', watts: 40 } },
    {
      id: 'cons-induct',
      type: 'consumer230v',
      position: { x: 980, y: 540 },
      data: { label: 'Induktionskochfeld', watts: 1200 },
    },
  ] as Node[],
  edges: [
    {
      id: 'e-batt-plus',
      source: 'battery-1',
      sourceHandle: 'plus',
      target: 'busbar-plus',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 0.5, crossSection: 70, fuseSize: 160 },
    },
    {
      id: 'e-batt-minus',
      source: 'battery-1',
      sourceHandle: 'minus',
      target: 'busbar-minus',
      targetHandle: 'minus',
      type: 'cableEdge',
      data: { length: 0.5, crossSection: 70 },
    },
    {
      id: 'e-solar-charger',
      source: 'solar-1',
      sourceHandle: 'plus',
      target: 'charger-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 4, crossSection: 6 },
    },
    {
      id: 'e-charger-busbar',
      source: 'charger-1',
      sourceHandle: 'plus',
      target: 'busbar-plus',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 10, fuseSize: 40 },
    },
    {
      id: 'e-starter-dcdc',
      source: 'starter-1',
      sourceHandle: 'plus',
      target: 'charger-2',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 5, crossSection: 16, fuseSize: 60 },
    },
    {
      id: 'e-dcdc-busbar',
      source: 'charger-2',
      sourceHandle: 'plus',
      target: 'busbar-plus',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 16, fuseSize: 50 },
    },
    {
      id: 'e-busbar-fuse',
      source: 'busbar-plus',
      sourceHandle: 'plus',
      target: 'fusebox-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 70, fuseSize: 160 },
    },
    {
      id: 'e-fuse-fridge',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-fridge',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 3, crossSection: 4 },
    },
    {
      id: 'e-fuse-heat',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-heat',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 4, crossSection: 4 },
    },
    {
      id: 'e-fuse-fan',
      source: 'fusebox-1',
      sourceHandle: 'plus',
      target: 'cons-fan',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 3, crossSection: 2.5 },
    },
    {
      id: 'e-busbar-inv-plus',
      source: 'busbar-plus',
      sourceHandle: 'plus',
      target: 'inverter-1',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 70, fuseSize: 160 },
    },
    {
      id: 'e-busbar-inv-minus',
      source: 'busbar-minus',
      sourceHandle: 'minus',
      target: 'inverter-1',
      targetHandle: 'minus',
      type: 'cableEdge',
      data: { length: 1, crossSection: 70 },
    },
    {
      id: 'e-inv-induct',
      source: 'inverter-1',
      sourceHandle: 'plus',
      target: 'cons-induct',
      targetHandle: 'plus',
      type: 'cableEdge',
      data: { length: 2, crossSection: 2.5, edgeDomain: 'AC_230V' },
    },
    {
      id: 'e-shore-inv',
      source: 'shore-1',
      sourceHandle: 'plus',
      target: 'inverter-1',
      targetHandle: 'ac_in',
      type: 'cableEdge',
      data: { length: 2, crossSection: 2.5, fuseSize: 16, edgeDomain: 'AC_230V' },
    },
  ] as Edge<CableEdgeData>[],
};

export const TEMPLATES_DICT: Record<string, { nodes: Node[]; edges: Edge<CableEdgeData>[] }> = {
  minimalist: TEMPLATE_MINIMALIST,
  allrounder: TEMPLATE_ALLROUNDER,
  autark: TEMPLATE_AUTARK,
};
